#!/bin/sh
zds_separator="="
zds_user_separator="/"
zds_get_os=$(uname -s)
zds_get_kernel_ver=$(uname -r)
zds_user=$(whoami)

zds_linux_fetch ()  { 
    printf "
   @    Za dom spremni! $zds_user_separator $zds_user 
 __@_   OS $zds_separator ZDS_Linux 
/    \  Kernel = $zds_get_os $zds_get_kernel_ver 
|    |  Shell = $SHELL 
|____| 
"
}

zds_netbsd_fetch () { 
    printf "
*------/           Za dom spremni! $zds_user_separator $zds_user 
*      |       |   OS = ZDS_BSD (NetBSD Version) 
*------|_______|   Kernel = $zds_separator $zds_get_kernel_ver 
*                  Shell $zds_separator $SHELL 
*                  
* \n"
}

zds_bsd_fetch () { 
    printf "
/           Za dom spremni! $zds_user_separator $zds_user 
|       |   OS = ZDS_BSD 
|_______|   Kernel $zds_separator $zds_get_os $zds_get_kernel_ver 
            Shell $zds_separator $SHELL 
"
}

zds_unknown_fetch () {
	printf "
 ##        Za dom spremni! $zds_user_separator $zds_user       
#  #       OS $zds_separator UNKNOWN ( $zds_get_os)
  #        Kernel $zds_separator $zds_get_os $zds_get_kernel_ver
  #        Shell $zds_separator $SHELL
     
  # 
"
}

if [ "$zds_get_os" = "Linux" ] || [ "$zds_get_os" = "Linux-zen" ] || [ "$zds_get_os" = "Linux-Libre" ] || [ "$zds_get_os" = "Linux Hardened" ] || [ "$zds_get_os" = "Linux LTS"; then
    zds_linux_fetch

elif [ "$zds_get_os" = "FreeBSD" ] || [ "$zds_get_os" = "OpenBSD" ] || [ "$zds_get_os" = "DragonFlyBSD" ] || [ "$zds_get_os" = "HardenedBSD" ] || [ "$zds_get_os" = "MidnightBSD" ] || [ "$zds_get_os" = "GhostBSD" ]; then
    zds_bsd_fetch
 
elif [ "$zds_get_os" = "NetBSD" ]; then
    zds_netbsd_fetch

else
	zds_unknown_fetch
fi

